# Generated by Django 5.0.6 on 2024-05-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='excursion_time',
            field=models.IntegerField(verbose_name='Время экскурсий'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='travel_time',
            field=models.IntegerField(verbose_name='Время в пути'),
        ),
    ]
